[package]
name = "iter-step-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-time = { version = "0.5", features = ["defmt"] }
defmt = "1.0"
thiserror = { version = "2.0", default-features = false }
