[target.riscv32imc-unknown-none-elf]
runner = "probe-rs attach --chip=esp32c3 --preverify --always-print-stacktrace --no-location --catch-hardfault"

[env]
DEFMT_LOG="error"
SSID="REPLACE"
PASSWORD="ME"
MQTT_USERNAME="REPLACE"
MQTT_PASSWORD="ME"
MQTT_BROKER_IP="10.10.0.3"
HOST_ID="crabroll-test"
MQTT_TOPIC_PREFIX="crabroll/test/"
COMMAND_TOPIC="crabroll/test/command"
POS_TOPIC="crabroll/test/pos"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "link-arg=-Tdefmt.x",
  "-C", "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
